# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - dev

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 4.2
    - nodejs_version: 5.3

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - cmd: npm test
  
build: off

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules