# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 1

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 4.2
    - nodejs_version: 5.3

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - cmd: npm test

matrix:
  fast_finish: true

deploy:

  - provider: FTP
    protocol: ftps
    host: waws-prod-bay-001.ftp.azurewebsites.windows.net
    username: csgdev\$csgdev
    password:
      secure: zLo6kp3AQmoevYxL63Na1WqbPT70ftR4n8hxfTW80e2KC8z2QqfHolzDvfu9
    folder: site/wwwroot
    active_mode: false
    on:
      branch: appveyor-test

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules